import { useState, useMemo } from 'react';
import {
  Download, Copy, Check, Code, FileText, GitBranch,
  Share2, Eye, ChevronDown, Filter
} from 'lucide-react';
import { useMemoryStore } from '../store/memoryStore';
import { Memory, MemoryCategory } from '../types';
import { CATEGORIES, CATEGORY_COLORS } from '../utils/constants';
import { cn } from '../utils/cn';

type ExportFormat = 'claude-md' | 'cursorrules' | 'json' | 'sharing-url';

interface FormatDef {
  id: ExportFormat;
  name: string;
  desc: string;
  icon: any;
  ext: string;
  color: string;
}

const FORMATS: FormatDef[] = [
  {
    id: 'claude-md',
    name: 'CLAUDE.md',
    desc: 'Markdown for Claude Code',
    icon: FileText,
    ext: '.md',
    color: 'from-orange-500/20 to-orange-600/10 border-orange-500/30 text-orange-300',
  },
  {
    id: 'cursorrules',
    name: '.cursorrules',
    desc: 'Plain text rules for Cursor',
    icon: Code,
    ext: '.cursorrules',
    color: 'from-blue-500/20 to-blue-600/10 border-blue-500/30 text-blue-300',
  },
  {
    id: 'json',
    name: 'JSON (MemGPT)',
    desc: 'MemGPT / Letta format',
    icon: GitBranch,
    ext: '.json',
    color: 'from-green-500/20 to-green-600/10 border-green-500/30 text-green-300',
  },
  {
    id: 'sharing-url',
    name: 'Sharing URL',
    desc: 'Read-only public snapshot',
    icon: Share2,
    ext: '.url',
    color: 'from-purple-500/20 to-purple-600/10 border-purple-500/30 text-purple-300',
  },
];

function generateClaudeMd(memories: Memory[], project: string): string {
  const byCategory: Partial<Record<MemoryCategory, Memory[]>> = {};
  memories.forEach(m => {
    if (!byCategory[m.category]) byCategory[m.category] = [];
    byCategory[m.category]!.push(m);
  });

  const sections = CATEGORIES
    .filter(cat => byCategory[cat]?.length)
    .map(cat => {
      const label = cat.charAt(0).toUpperCase() + cat.slice(1);
      const items = byCategory[cat]!.map(m => `- ${m.content}`).join('\n');
      return `## ${label}\n\n${items}`;
    });

  return `# Agent Memory — ${project}\n\n> Auto-generated by AgentMemory.fyi\n\n${sections.join('\n\n')}`;
}

function generateCursorRules(memories: Memory[]): string {
  const byCategory: Partial<Record<MemoryCategory, Memory[]>> = {};
  memories.forEach(m => {
    if (!byCategory[m.category]) byCategory[m.category] = [];
    byCategory[m.category]!.push(m);
  });

  const sections = CATEGORIES
    .filter(cat => byCategory[cat]?.length)
    .map(cat => {
      const label = cat.toUpperCase();
      const items = byCategory[cat]!.map(m => `- ${m.content}`).join('\n');
      return `# ${label}\n${items}`;
    });

  return `# Cursor Rules — Generated by AgentMemory.fyi\n\n${sections.join('\n\n---\n\n')}`;
}

function generateMemGPTJson(memories: Memory[], project: string): string {
  const data = {
    version: '1.0',
    generator: 'agentmemory.fyi',
    project,
    exported_at: new Date().toISOString(),
    memories: memories.map(m => ({
      id: m.id,
      content: m.content,
      category: m.category,
      source: m.source,
      tags: m.tags,
      importance: m.importance || 3,
      created_at: m.created_at,
    })),
    metadata: {
      total: memories.length,
      categories: Object.fromEntries(
        CATEGORIES.map(cat => [cat, memories.filter(m => m.category === cat).length])
      ),
    },
  };
  return JSON.stringify(data, null, 2);
}

function generateSharingUrl(memories: Memory[], project: string): string {
  const snapshot = {
    project,
    memories: memories.map(m => ({ content: m.content, category: m.category, tags: m.tags })),
    created_at: new Date().toISOString(),
  };
  const encoded = btoa(JSON.stringify(snapshot)).slice(0, 64) + '...';
  return `https://agentmemory.fyi/shared/${encoded}`;
}

export default function ExportPage() {
  const { memories, projects, activeProject } = useMemoryStore();
  const [selectedFormat, setSelectedFormat] = useState<ExportFormat>('claude-md');
  const [selectedProject, setSelectedProject] = useState<string>(activeProject);
  const [filterCategory, setFilterCategory] = useState<MemoryCategory | 'all'>('all');
  const [copied, setCopied] = useState(false);
  const [showProjectDropdown, setShowProjectDropdown] = useState(false);

  const filteredMemories = useMemo(() => {
    let mems = memories.filter(m => m.project_name === selectedProject || selectedProject === 'all');
    if (filterCategory !== 'all') mems = mems.filter(m => m.category === filterCategory);
    return mems;
  }, [memories, selectedProject, filterCategory]);

  const exportContent = useMemo(() => {
    switch (selectedFormat) {
      case 'claude-md': return generateClaudeMd(filteredMemories, selectedProject);
      case 'cursorrules': return generateCursorRules(filteredMemories);
      case 'json': return generateMemGPTJson(filteredMemories, selectedProject);
      case 'sharing-url': return generateSharingUrl(filteredMemories, selectedProject);
      default: return '';
    }
  }, [selectedFormat, filteredMemories, selectedProject]);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(exportContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([exportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    const fileName = selectedFormat === 'claude-md' ? 'CLAUDE.md' :
      selectedFormat === 'cursorrules' ? '.cursorrules' :
      selectedFormat === 'json' ? `agentmemory-${selectedProject.replace(/\s+/g, '-').toLowerCase()}.json` :
      'sharing-url.txt';
    a.download = fileName;
    a.click();
    URL.revokeObjectURL(url);
  };

  const categoryStats = useMemo(() => {
    return CATEGORIES.map(cat => ({
      cat,
      count: filteredMemories.filter(m => m.category === cat).length,
    })).filter(s => s.count > 0);
  }, [filteredMemories]);

  return (
    <div className="p-6 max-w-6xl mx-auto">
      {/* Header */}
      <div className="mb-8">
        <h1 className="text-2xl font-bold text-white mb-2">Export Memories</h1>
        <p className="text-sm text-gray-400">
          Export your memories to any AI agent format — Claude Code, Cursor, MemGPT, or shareable links.
        </p>
      </div>

      <div className="grid lg:grid-cols-3 gap-6">
        {/* Left: Settings */}
        <div className="space-y-6">
          {/* Format Selection */}
          <div>
            <h3 className="text-sm font-medium text-gray-300 mb-3">Export Format</h3>
            <div className="space-y-2">
              {FORMATS.map(format => (
                <button
                  key={format.id}
                  onClick={() => setSelectedFormat(format.id)}
                  className={cn(
                    'w-full flex items-center gap-3 p-3 rounded-xl border transition-all text-left',
                    selectedFormat === format.id
                      ? `bg-gradient-to-r ${format.color}`
                      : 'bg-gray-900 border-gray-700 text-gray-400 hover:border-gray-600 hover:text-gray-300'
                  )}
                >
                  <div className={cn('p-2 rounded-lg', selectedFormat === format.id ? 'bg-white/10' : 'bg-gray-800')}>
                    <format.icon size={16} />
                  </div>
                  <div>
                    <p className="text-sm font-medium">{format.name}</p>
                    <p className="text-xs opacity-70">{format.desc}</p>
                  </div>
                  {selectedFormat === format.id && (
                    <div className="ml-auto w-2 h-2 rounded-full bg-current opacity-70" />
                  )}
                </button>
              ))}
            </div>
          </div>

          {/* Project Selection */}
          <div>
            <h3 className="text-sm font-medium text-gray-300 mb-3">Project</h3>
            <div className="relative">
              <button
                onClick={() => setShowProjectDropdown(!showProjectDropdown)}
                className="w-full flex items-center gap-2 px-3 py-2.5 bg-gray-900 border border-gray-700 rounded-xl text-sm text-gray-300 hover:border-gray-600"
              >
                <Filter size={14} className="text-gray-400" />
                <span className="flex-1 text-left">{selectedProject === 'all' ? 'All Projects' : selectedProject}</span>
                <ChevronDown size={14} className={cn('text-gray-400 transition-transform', showProjectDropdown && 'rotate-180')} />
              </button>
              {showProjectDropdown && (
                <div className="absolute top-full left-0 right-0 mt-1 bg-gray-800 border border-gray-700 rounded-xl shadow-xl z-10 overflow-hidden">
                  {['all', ...projects].map(p => (
                    <button
                      key={p}
                      onClick={() => { setSelectedProject(p); setShowProjectDropdown(false); }}
                      className={cn(
                        'w-full px-3 py-2 text-sm text-left transition-colors',
                        selectedProject === p ? 'text-indigo-400 bg-indigo-500/10' : 'text-gray-300 hover:bg-gray-700'
                      )}
                    >
                      {p === 'all' ? 'All Projects' : p}
                    </button>
                  ))}
                </div>
              )}
            </div>
          </div>

          {/* Category Filter */}
          <div>
            <h3 className="text-sm font-medium text-gray-300 mb-3">Filter Categories</h3>
            <div className="flex flex-wrap gap-1.5">
              <button
                onClick={() => setFilterCategory('all')}
                className={cn('px-2 py-1 rounded-lg text-xs border transition-all',
                  filterCategory === 'all' ? 'bg-indigo-600/20 border-indigo-500/50 text-indigo-300' : 'bg-gray-800 border-gray-700 text-gray-400')}
              >
                All
              </button>
              {CATEGORIES.map(cat => (
                <button
                  key={cat}
                  onClick={() => setFilterCategory(cat)}
                  className={cn('px-2 py-1 rounded-lg text-xs border transition-all',
                    filterCategory === cat
                      ? 'border-current text-white'
                      : 'bg-gray-800 border-gray-700 text-gray-500 hover:border-gray-600 hover:text-gray-400'
                  )}
                  style={filterCategory === cat ? { backgroundColor: CATEGORY_COLORS[cat] + '33', color: CATEGORY_COLORS[cat], borderColor: CATEGORY_COLORS[cat] + '80' } : {}}
                >
                  {cat}
                </button>
              ))}
            </div>
          </div>

          {/* Stats */}
          <div className="bg-gray-900 border border-gray-800 rounded-xl p-4">
            <h3 className="text-sm font-medium text-gray-300 mb-3">Export Summary</h3>
            <div className="space-y-2">
              <div className="flex justify-between text-sm">
                <span className="text-gray-400">Total memories</span>
                <span className="text-white font-medium">{filteredMemories.length}</span>
              </div>
              {categoryStats.map(({ cat, count }) => (
                <div key={cat} className="flex justify-between text-xs">
                  <span className="text-gray-500 capitalize">{cat}</span>
                  <span className="text-gray-300">{count}</span>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Right: Preview */}
        <div className="lg:col-span-2">
          <div className="bg-gray-900 border border-gray-800 rounded-xl overflow-hidden h-full flex flex-col">
            {/* Preview Header */}
            <div className="flex items-center justify-between px-4 py-3 border-b border-gray-800 bg-gray-900">
              <div className="flex items-center gap-2">
                <Eye size={14} className="text-gray-400" />
                <span className="text-sm font-medium text-gray-300">Preview</span>
                <span className="text-xs text-gray-500 font-mono">
                  {FORMATS.find(f => f.id === selectedFormat)?.ext}
                </span>
              </div>
              <div className="flex items-center gap-2">
                <button
                  onClick={handleCopy}
                  className={cn(
                    'flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs border transition-all',
                    copied
                      ? 'bg-green-600/20 border-green-500/50 text-green-400'
                      : 'bg-gray-800 border-gray-700 text-gray-300 hover:border-gray-600'
                  )}
                >
                  {copied ? <Check size={12} /> : <Copy size={12} />}
                  {copied ? 'Copied!' : 'Copy'}
                </button>
                <button
                  onClick={handleDownload}
                  className="flex items-center gap-1.5 px-3 py-1.5 bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg text-xs transition-colors"
                >
                  <Download size={12} />
                  Download
                </button>
              </div>
            </div>

            {/* Code preview */}
            <div className="flex-1 overflow-auto">
              {selectedFormat === 'sharing-url' ? (
                <div className="p-6 flex flex-col items-center justify-center min-h-[300px] text-center">
                  <Share2 size={40} className="text-purple-400 mb-4" />
                  <h3 className="text-lg font-medium text-white mb-2">Read-Only Snapshot</h3>
                  <p className="text-sm text-gray-400 mb-6">
                    Creates a shareable link with a read-only view of your selected memories.
                  </p>
                  <div className="w-full max-w-md bg-gray-800 border border-gray-700 rounded-xl p-3 text-left">
                    <p className="text-xs text-gray-400 mb-1 font-mono">Sharing URL:</p>
                    <p className="text-sm text-purple-400 font-mono break-all">{exportContent}</p>
                  </div>
                  <button
                    onClick={handleCopy}
                    className="mt-4 flex items-center gap-2 px-4 py-2 bg-purple-600 hover:bg-purple-700 text-white rounded-lg text-sm"
                  >
                    {copied ? <Check size={14} /> : <Copy size={14} />}
                    {copied ? 'Copied!' : 'Copy URL'}
                  </button>
                </div>
              ) : (
                <pre className="p-4 text-xs text-gray-300 font-mono leading-relaxed whitespace-pre-wrap overflow-x-auto">
                  {exportContent || <span className="text-gray-600">No memories to export with selected filters.</span>}
                </pre>
              )}
            </div>

            {/* Footer */}
            {selectedFormat !== 'sharing-url' && (
              <div className="px-4 py-3 border-t border-gray-800 bg-gray-900/50">
                <div className="flex items-center justify-between text-xs text-gray-500">
                  <span>
                    {exportContent.split('\n').length} lines • {(exportContent.length / 1024).toFixed(1)} KB
                  </span>
                  <span className="flex items-center gap-1">
                    Generated by AgentMemory.fyi
                  </span>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
